### ISSUE TITLE
[Feature request] IPv6 Support

### ISSUE THREAD

**Issue by jeffbrl** [mxmlndml/cloudflare-dynamic-dns#1]
Thank you for writing and sharing this software. Enhancing the code to support (and prefer) IPv6 would be great. I tried doing this myself but my JS skills are rusty.

**Comment by mxmlndml** [comment]
Thanks for the feedback! Since I wanted to dive a bit into Go I rewrote the application and managed to add IPv6/AAAA record support. Now you can edit the `RECORD_TYPES` environment variable to either support IPv4/A records or IPv6/AAAA records or both.

**Comment by jeffbrl** [comment]
Awesome! Thank you. Will open issues if encounter defects.
